### ISSUE TITLE
openid 0.5.6 Breaks passport-openid

### ISSUE THREAD

**Issue by kopertop** [jaredhanson/passport-openid#26]
Trying with a fresh install, npm installs openid 0.5.6, which breaks Passport-openid (at least when used with passport-google). It looks like there might be something called twice with openid, which returns an error first, then the successful message, but the error happens first so that causes login to fail.

Here's the traceback:

```
Failed to verify assertion (message: No providers were discovered for the claimed identifier)
at /var/app/current/node_modules/passport-google/node_modules/passport-openid/lib/passport-openid/strategy.js:184:36
at /var/app/current/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1061:12
at /var/app/current/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1148:14
at /var/app/current/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:678:7
at /var/app/current/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:544:16
at done (/var/app/current/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:254:9)
at IncomingMessage.<anonymous> (/var/app/current/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:258:32)
at IncomingMessage.EventEmitter.emit (events.js:117:20)
at _stream_readable.js:910:16
at /var/app/current/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31
```

Changing package.json to require openid 0.5.5 fixes this issue.

**Comment by jaredhanson** [comment]
Published package which requires `openid@1.x.x` to npm as `passport-openid@0.4.0`.
