### ISSUE TITLE
Example not working with Express v4.x

### ISSUE THREAD

**Issue by AntouanK** [jaredhanson/passport-openid#31]
Hi.

The example you have in the repo, needs express v3.x in order to work. API has changed in v4.

Should I make a PR to change that [line](https://github.com/jaredhanson/passport-openid/blob/master/examples/signon/package.json#L5)?

Also, I don't see how the example works.
After giving a name, I get an error at `http://localhost:3000/auth/openid`

```HTML
InternalOpenIDError: Failed to discover OP endpoint URL
   at /Users/antouank/_REPOS_/passport-openid/examples/signon/node_modules/passport-openid/lib/passport-openid/strategy.js:249:52
   at /Users/antouank/_REPOS_/passport-openid/examples/signon/node_modules/passport-openid/node_modules/openid/openid.js:874:14
   at /Users/antouank/_REPOS_/passport-openid/examples/signon/node_modules/passport-openid/node_modules/openid/openid.js:664:13
   at /Users/antouank/_REPOS_/passport-openid/examples/signon/node_modules/passport-openid/node_modules/openid/openid.js:620:11
   at ClientRequest.<anonymous> (/Users/antouank/_REPOS_/passport-openid/examples/signon/node_modules/passport-openid/node_modules/openid/openid.js:266:12)
   at emitOne (events.js:77:13)
   at ClientRequest.emit (events.js:166:7)
   at Socket.socketErrorListener (_http_client.js:254:9)
   at emitOne (events.js:77:13)
   at Socket.emit (events.js:166:7)
```

**Comment by jaredhanson** [comment]
I've moved the example, which is now pegged to Express 3.x here: https://github.com/passport/express-3.x-openid-example

The error you report indicates that the OpenID identifier you used was not valid.
