### ISSUE TITLE
Update OpenID dependency to 2.0.1

### ISSUE THREAD

**Issue by aport** [jaredhanson/passport-openid#35]
passport-openid is broken on Node V6. Updating openid to v2.0.1 will fix this.

**Comment by ha1331** [comment]
Would love if this was fixed sooner rather than later. Spent multiple hours (embarrassing amount of hours) figuring out why I wasn't able to get even the simplest of example codes run without crashing. Other than that, thanks for the the work you guys have done providing this software for the community.

**Comment by Noiwex** [comment]
Is author dead? I'm gonna take npm repo.

**Comment by Martii** [comment]
@jaredhanson 
It would appear that we might be encountering this issue in our production environment as well but not entirely sure here:

``` sh-session
TypeError: params.hasOwnProperty is not a function
    at _checkSignatureUsingProvider (~/OpenUserJS.org/node_modules/openid/openid.js:1289:15)
    at _checkSignature (~/OpenUserJS.org/node_modules/openid/openid.js:1224:5)
    at _verifyAssertionAgainstProviders (~/OpenUserJS.org/node_modules/openid/openid.js:1188:12)
    at ~/OpenUserJS.org/node_modules/openid/openid.js:1153:7
    at ~/OpenUserJS.org/node_modules/openid/openid.js:686:7
    at ~/OpenUserJS.org/node_modules/openid/openid.js:541:11
    at done (~/OpenUserJS.org/node_modules/openid/openid.js:258:9)
    at IncomingMessage.<anonymous> (~/OpenUserJS.org/node_modules/openid/openid.js:262:32)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Our deps at depth 0 that are still openid based and not oauth based, that we still currently use, are [*passport-steam*](https://github.com/liamcurry/passport-steam) *(which seems to work with a test account although had one error on their end but a retry seems to have fixed that)*, [*passport-yahoo*](https://github.com/jaredhanson/passport-yahoo) and [*passport-aol*](http://github.com/jaredhanson/passport-aol) *(these last two are your projects)*.

Please let us know if you need any additional intel and thanks in advance for the relook.

**Comment by johngeorgewright** [comment]
👍 Having the same issue.

**Comment by Noiwex** [comment]
npm install https://github.com/Noiwex/passport-openid

**Comment by poikilos** [comment]
@Noiwex there was no PR so I made one: https://github.com/jaredhanson/passport-openid/pull/43

**Comment by rwky** [comment]
Forked and fixed in https://github.com/passport-next/passport-openid

Install with npm install @passport-next/passport-openid
