### ISSUE TITLE
 Failed to discover OP endpoint URL : passport-ibm

### ISSUE THREAD

**Issue by indranipinks** [jaredhanson/passport-openid#39]
We have a Node.js application hosted on Bluemix. It uses IBM Tivoli Federated Identity Manager as the authentication service and uses OpenID. We use passport-ibm Node module at the backend for this. The authentication used to work properly till last week. But suddenly it stopped working and is throwing error even before showing the login screen.

Here is the stack trace:
2017-11-20T16:07:42.50+0530 [APP/PROC/WEB/0]ERR InternalOpenIDError: Failed to discover OP endpoint URL 2017-11-20T16:07:42.50+0530 [APP/PROC/WEB/0]ERR at ClientRequest. (/home/vcap/app/node_modules/passport-ibm/node_modules/passport-openid/node_modules/openid/openid.js:266:12) 2017-11-20T16:07:42.50+0530 [APP/PROC/WEB/0]ERR at TLSSocket.socketErrorListener (_http_client.js:269:9) 2017-11-20T16:07:42.50+0530 [APP/PROC/WEB/0]ERR at TLSSocket.emit (events.js:169:7) 2017-11-20T16:07:42.50+0530 [APP/PROC/WEB/0]ERR at /home/vcap/app/node_modules/passport-ibm/node_modules/passport-openid/lib/passport-openid/strategy.js:249:52 2017-11-20T16:07:42.50+0530 [APP/PROC/WEB/0]ERR at /home/vcap/app/node_modules/passport-ibm/node_modules/passport-openid/node_modules/openid/openid.js:664:13 2017-11-20T16:07:42.50+0530 [APP/PROC/WEB/0]ERR at /home/vcap/app/node_modules/passport-ibm/node_modules/passport-openid/node_modules/openid/openid.js:620:11 2017-11-20T16:07:42.50+0530 [APP/PROC/WEB/0]ERR at emitOne (events.js:77:13) 2017-11-20T16:07:42.50+0530 [APP/PROC/WEB/0]ERR at /home/vcap/app/node_modules/passport-ibm/node_modules/passport-openid/node_modules/openid/openid.js:874:14 2017-11-20T16:07:42.50+0530 [APP/PROC/WEB/0]ERR at emitOne (events.js:77:13) 2017-11-20T16:07:42.50+0530 [APP/PROC/WEB/0]ERR at ClientRequest.emit (events.js:169:7)

I googled the issue and found one solution is to use - 'stateless:true' attribute but that also didn't help.

Our entire production is down because clients cannot go past the authentication and hence cannot access the application.
Can you please suggest something?

**Comment by HananeAlSamrout** [comment]
have you had any luck solving this?
