### ISSUE TITLE
InternalOpenIDError: Failed to verify assertion

### ISSUE THREAD

**Issue by nickhall** [jaredhanson/passport-openid#45]
I know that this package is basically dead, but some kind of fix for this would be vastly appreciated.

passport-openid@^0.4.0

```
InternalOpenIDError: Failed to verify assertion
    at /Users/username/development/askdoctors-corporate/corporate/node_modules/passport-openid/lib/passport-openid/strategy.js:184:36
    at /Users/username/development/askdoctors-corporate/corporate/node_modules/openid/openid.js:981:12
    at /Users/username/development/askdoctors-corporate/corporate/node_modules/openid/openid.js:1063:16
    at /Users/username/development/askdoctors-corporate/corporate/node_modules/openid/openid.js:577:13
    at /Users/username/development/askdoctors-corporate/corporate/node_modules/openid/openid.js:546:13
    at _parseHostMeta (/Users/username/development/askdoctors-corporate/corporate/node_modules/openid/openid.js:421:5)
    at /Users/username/development/askdoctors-corporate/corporate/node_modules/openid/openid.js:541:9
    at Request._callback (/Users/username/development/askdoctors-corporate/corporate/node_modules/openid/openid.js:228:7)
    at Request.self.callback (/Users/username/development/askdoctors-corporate/corporate/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/username/development/askdoctors-corporate/corporate/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/username/development/askdoctors-corporate/corporate/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by rwky** [comment]
@nickhall can you give this fork a go https://github.com/passport-next/passport-openid and see if you have the same problem, if you do raise an issue there.

**Comment by soorur** [comment]
Bump :)
